### ISSUE TITLE
MissingPluginException(No implementation found for method getId on channel android_id)

### ISSUE THREAD

**Issue by tushartripathi** [fluttercommunity/android_id#60]
code

`const _androidIdPlugin = AndroidId(); 
    serialNumber = await _androidIdPlugin.getId();
    print(serialNumber);`

error

`E/flutter (24501): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method getId on channel android_id)
E/flutter (24501): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
E/flutter (24501): <asynchronous suspension>
E/flutter (24501): #1      _AddEmailState.getFlutterId (package:zaperon_finlock/pages/AddEmail.dart:331:20)
E/flutter (24501): <asynchronous suspension>`

**Comment by nohli** [comment]
Hi @tushartripathi!

Thanks for opening this issue.

On which platform are you experiencing this exception?

**Comment by nohli** [comment]
I guess it was because calling `getID()` on a platform different than Android.

This is fixed in the latest version.

**Comment by vipinnegi90** [comment]
![image](https://github.com/fluttercommunity/android_id/assets/19855111/5df8c0f9-de49-48e5-b676-aaedcb36e16a)
Can see this issue even on Android.

**Comment by nohli** [comment]
Please provide a minimal, reproducible example for debugging 🙏🏽

**Comment by amd110** [comment]
我在Android上也遇到同样的问题

**Comment by nohli** [comment]
@subzero911 @FangHanZreo @tushartripathi @vipinnegi90 @joaovirgilicw @amd110 - I tagged everyone that participated in the two issues regarding MissingPluginException

So far no one has provided a minimal reproducible sample, making it very hard to debug and help you.

If you still have this issue, there are three things I would like you to check:

1. In your pubspec.yaml, use the latest version:
```
  android_id: ^0.5.1
```

2. In your pubspec.yaml, use another branch:
```
  android_id:
    git:
      url: https://github.com/fluttercommunity/android_id.git
      ref: missing-plugin-exception
```

3. Check if the issue is because you still have the v1 embedding:

> Open android/app/src/main/.../MainActivity and check the import - if it says io.flutter.app.FlutterActivity, you’re still on the legacy embedding and that’s why this
  plugin never registers. Follow the migration steps here: https://github.com/flutter/flutter/blob/main/docs/platforms/android/Upgrading-pre-1.12-Android-projects.md (or easier: delete and regenerate the Android folder with
  `flutter create .` after backing up your changes) to move to the v2 embedding.

If nothing works, please let me know the Flutter version you're using, and if this also happens in a new project - if not, please at least provide the output of `flutter run`, the imported packages in `pubspec.yaml`, and ideally some `Dart code` with your implementation.
